Correction compilation frontend
Ceci corrige l'erreur suivante

frontend_1  | ERROR in src/app/components/backlog/create-issue/create-issue.component.ts(16,14): error TS2420: Class 'CreateIssueComponent' incorrectly implements interface 'OnInit'.
frontend_1  |   Property 'ngOnInit' is missing in type 'CreateIssueComponent'.